apiVersion: v1
kind: Secret
metadata:
  name: payment-ctseapp-secrets
type: Opaque
stringData:
  MONGO_URL: mongodb+srv://nithya123:nithya123@cluster0.vcabd.mongodb.net/ctse?retryWrites=true&w=majority
